#!/bin/sh
# Running golangci-lint
printf "Running golangci-lint\n"
golangci-lint run --tests=0 ./...

# Running golangci-lint
printf "Running go mod tidy\n"
go mod tidy

// Running git add -A
printf "Running git add -A\n"
git add -A
