#!/bin/sh

# Creating a variable of all the files that have been changed
STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")

# Checking if there are any staged files
if [[ "$STAGED_GO_FILES" = "" ]]; then
  exit 0
fi

PASS=true

# Looping through all the staged files
for FILE in $STAGED_GO_FILES
do
    golangci-lint run --tests=0 ./...
    if [ $? -ne 0 ]; then
        PASS=false
    fi
done

if ! $PASS; then
  printf "❌ Commit Failed with the above error, Please fix and Retry\n"
  exit 1
fi

exit 0
